### PR TITLE
Add Subsonic support

### PR DESCRIPTION
**Pull request by jonaski**

### CODE REVIEW

**Comment by llucps** [comment]
Hi Jonaski,

Thank you very much to add Subsonic API support! I appreciated very much.

I downloaded the latest build for macOS and I can't connect to my Airsonic server. This is the error I get:

error-subsonic

My Airsonic runs on Debian stretch, tomcat 8 under https (port 443) using a lets encrypt certificate,  under a sub directory.. so https://example.com/airsonic.

I've checked the logs but nothing.

Any ideas what could it be?

Thanks!

**Comment by jonaski** [comment]
My code didn't allow a sub path, should be fixed now https://github.com/jonaski/strawberry/commit/dabd6f828454e946b5b2472755ed108d3c9adea4

**Comment by llucps** [comment]
Thank you.. ! but it seems today is not my day  :)

I get the message with the last Airsonic version avaialable 10.3.1

Screenshot 2019-06-18 at 18 36 55

Thanks.

**Comment by jonaski** [comment]
I set the api version too high, Airsonic is using 1.15.0. I've set it to 1.15.0 now.
https://github.com/jonaski/strawberry/commit/d27a3f1f33e1a768f66618db273e460c569cf375

**Comment by llucps** [comment]
Thank you, it works perfectly.

**Pull request merged**
